server:
  port: 8085
  ip: 192.168.43.250
  protocol: http
spring:
  datasource:
    username: root2
    password: 123456
    #
    url: jdbc:mysql://47.120.39.45:3306/calligraphy_evaluation_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    # yyyy-MM-dd HH:mm:ss 格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 毫秒时间戳格式
      write-dates-as-timestamps: true
mybatis:
  mapper-locations: classpath:mapper/*.xml   #
#
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.moyunzhijiao.system_frontend
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
